# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.1.2
maven_group=safe.flerovium

# Dependencies
fabric_api_version=0.155.2+26.2
mixin_extras_version=0.5.4

# Sodium - from CaffeineMC Maven (https://maven.caffeinemc.net/releases/net/caffeinemc/sodium-fabric/)
sodium_version=0.9.1+mc26.2

# Iris - from Iris Maven (https://maven.irisshaders.dev/releases/net/irisshaders/iris/)
iris_version=1.11.2+26.2
